### ISSUE TITLE
How to install your live_plotter library? 

### ISSUE THREAD

**Issue by jS5t3r** [paulyehtw/Motion-Planning-on-CARLA#1]
I get the following error:

```
➜  Motion-Planning-on-CARLA git:(master) ✗ python3 module_7.py 
Traceback (most recent call last):
  File "module_7.py", line 34, in <module>
    import live_plotter as lv   # Custom live plotting library
ImportError: No module named 'live_plotter'
```

How to install your custom live plotter?

**Comment by paulyehtw** [comment]
Hi,
Did you install the CARLA simulator?

**Comment by paulyehtw** [comment]
@jS5t3r CARLA Simulator can be downloaded from https://www.coursera.org/learn/motion-planning-self-driving-cars

**Comment by jS5t3r** [comment]
Yes, I have installed Carla 0.9.6 precompiled.

**Comment by paulyehtw** [comment]
@jS5t3r in case it still doesnt work for you, please download the simulator here : https://drive.google.com/file/d/1XflJ5AtZ5YIIBmorSdhYcEjENrY1sJJN/view

**Comment by jS5t3r** [comment]
@paulyehtw  I had to copy the file into the `PythonClient` folder (/CarlaSimulator/PythonClient/Course1FinalProject)

**Comment by aravindSwamy94** [comment]
Hi @paulyehtw : I have the same problem. 
I cannot find the live_plotter script .
Can you please help me with that

**Comment by eli-halych** [comment]
You need to place all files provided for the project under `CarlaSimulator/PythonClient/Course4FinalProject/`. Then cd into this folder and only then run `python module_7.py`.  live_plotter is a .py file and the problem is that it just doesn't see it.

**Comment by Anupam-Bangal** [comment]
hey i tried all the steps but it throws an error.
C:\Users\HP\Coursera\CarlaSimulator\PythonClient\Course1FinalProject>python module_7.py
Traceback (most recent call last):
  File "C:\Users\HP\Coursera\CarlaSimulator\PythonClient\Course1FinalProject\module_7.py", line 33, in <module>
    import live_plotter as lv   # Custom live plotting library
  File "C:\Users\HP\Coursera\CarlaSimulator\PythonClient\live_plotter.py", line 8, in <module>
    import matplotlib.backends.tkagg as tkagg
ModuleNotFoundError: No module named 'matplotlib.backends.tkagg'

can anyone please help me...

**Comment by datonefaridze** [comment]
@Anupam-Bangal I have the same problem :(

**Comment by taoufikayoub** [comment]
@Anupam-Bangal @datonefaridze 
Try This:
import matplotlib.backends.backend_tkagg as tkagg
from matplotlib.backends.backend_tkagg import FigureCanvasAgg

**Comment by olyii** [comment]
> @Anupam-Bangal @datonefaridze Try This: import matplotlib.backends.backend_tkagg as tkagg from matplotlib.backends.backend_tkagg import FigureCanvasAgg

AttributeError: module 'matplotlib.backends.backend_tkagg' has no attribute 'blit'.............how to sovle it?

**Comment by olyii** [comment]
> hey i tried all the steps but it throws an error. C:\Users\HP\Coursera\CarlaSimulator\PythonClient\Course1FinalProject>python module_7.py Traceback (most recent call last): File "C:\Users\HP\Coursera\CarlaSimulator\PythonClient\Course1FinalProject\module_7.py", line 33, in import live_plotter as lv # Custom live plotting library File "C:\Users\HP\Coursera\CarlaSimulator\PythonClient\live_plotter.py", line 8, in import matplotlib.backends.tkagg as tkagg ModuleNotFoundError: No module named 'matplotlib.backends.tkagg'
> 
> can anyone please help me...

AttributeError: module 'matplotlib.backends.backend_tkagg' has no attribute 'blit'  .....how to sovle it?

**Comment by eakbangash** [comment]
> > hey i tried all the steps but it throws an error. C:\Users\HP\Coursera\CarlaSimulator\PythonClient\Course1FinalProject>python module_7.py Traceback (most recent call last): File "C:\Users\HP\Coursera\CarlaSimulator\PythonClient\Course1FinalProject\module_7.py", line 33, in import live_plotter as lv # Custom live plotting library File "C:\Users\HP\Coursera\CarlaSimulator\PythonClient\live_plotter.py", line 8, in import matplotlib.backends.tkagg as tkagg ModuleNotFoundError: No module named 'matplotlib.backends.tkagg'
> > can anyone please help me...
> 
> AttributeError: module 'matplotlib.backends.backend_tkagg' has no attribute 'blit' .....how to sovle it?

have you solved the problem
