### ISSUE TITLE
Where to find the live_plotter library

### ISSUE THREAD

**Issue by muhenan** [paulyehtw/Motion-Planning-on-CARLA#2]
Your projects are great. But I really don't know where to find the live_plotter library.
Thank you.

**Comment by paulyehtw** [comment]
@muhenan Please download the simulator with `live_plotter` [here](https://drive.google.com/file/d/1XflJ5AtZ5YIIBmorSdhYcEjENrY1sJJN/view?usp=sharing)

**Comment by aravindSwamy94** [comment]
Hi @paulyehtw : I cannot download this from the link you have mentioned above. 
can you please let me know where can I find it

**Comment by paulyehtw** [comment]
Please register [this course](https://www.coursera.org/learn/motion-planning-self-driving-cars) on Coursera, it provides the CARLA specifically for this usage
