### ISSUE TITLE
Having Problem with Importing Carla Dependencies

### ISSUE THREAD

**Issue by KasraMokhtari2112** [paulyehtw/Motion-Planning-on-CARLA#3]
Hi @paulyehtw,

Thanks for sharing your code. This is a great project. I am just having a problem with importing Carla dependencies, specifically these lines:
from carla            import sensor
from carla.client     import make_carla_client, VehicleControl
from carla.settings   import CarlaSettings
from carla.tcp        import TCPConnectionError)

which version of Carla are you using? where can I get these files? Thank you so much for your time and help.

**Comment by HuangSecretKey** [comment]
> Hi @paulyehtw,
> 
> Thanks for sharing your code. This is a great project. I am just having a problem with importing Carla dependencies, specifically these lines:
> from carla import sensor
> from carla.client import make_carla_client, VehicleControl
> from carla.settings import CarlaSettings
> from carla.tcp import TCPConnectionError)
> 
> which version of Carla are you using? where can I get these files? Thank you so much for your time and help.

I also meet this problem，and have you solved it.

**Comment by AD1D1** [comment]
Traceback (most recent call last):
  File "module_7.py", line 43, in <module>
    from carla            import sensor
ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla\__init__.py)

**Comment by paulyehtw** [comment]
Please register [this course](https://www.coursera.org/learn/motion-planning-self-driving-cars) on Coursera, it provides the CARLA specifically for this usage

**Comment by KuldeepDileep** [comment]
> Please register [this course](https://www.coursera.org/learn/motion-planning-self-driving-cars) on Coursera, it provides the CARLA specifically for this usage

@paulyehtw Is there any other way way to install the CARLA simulator provided by the course on Coursera? I have installed Carla from [here](https://github.com/carla-simulator/carla/blob/master/Docs/download.md)
