### ISSUE TITLE
cannot import name 'sensor' from 'carla'

### ISSUE THREAD

**Issue by KuldeepDileep** [paulyehtw/Motion-Planning-on-CARLA#4]
I have unzipped the content of this repository in /home/kuldeep/Downloads/CARLA_0.9.10/PythonAPI though it says to put the folder in PythonClient but I don't have that folder in my CARLA_0.9.10 so I have cloned it in PythonAPI folder. When I execute module_7.py file from there I get this error:
ImportError: cannot import name 'sensor' from 'carla' (/home/kuldeep/Downloads/CARLA_0.9.10/PythonAPI/carla/dist/carla-0.9.10-py3.7-linux-x86_64/carla/init.py)

Would appreciate any help!

**Comment by gsg213** [comment]
Hi @KuldeepDileep , how did you solve the issue?

Did you have to change CARLA's version?

**Comment by Euphyx** [comment]
> Hi @KuldeepDileep , how did you solve the issue?
> 
> Did you have to change CARLA's version?

Hello @gsg213, did you solve this issue? I have the same problem.

**Comment by gsg213** [comment]
> > Hi @KuldeepDileep , how did you solve the issue?
> > Did you have to change CARLA's version?
> 
> Hello @gsg213, did you solve this issue? I have the same problem.

Hello @Euphyx, the problem is CARLA's version you are using, you have to use the version given in Coursera's [Self-Driving Cars Specialization](https://www.coursera.org/specializations/self-driving-cars).
